server:
  port: 8090

spring:
  application:
    name: config-client
  cloud:
    config:
      uri: http://localhost:8097
      profile: default
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8091/eureka/
