server:
  port: 8605
spring:
  application:
    name: stream-producer
  cloud:
    stream:

      binders:
        defaultRabbit: # 表示定义的名称，用于于binding整合
          type: rabbit # 消息组件类型
      default-binder: defaultRabbit
#          environment: # 设置rabbitmq的相关的环境配置
#            spring:
#              rabbitmq:
#                addresses: 149.28.142.66
#                username: guest
#                password: guest
#                virtual-host: /
      bindings: # 服务的整合处理
        output: # 这个名字是一个接收通道的名称
          destination: logExchange # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为对象json，如果是文本则设置“text/plain”
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
          acknowledge-mode: auto123
        logOutput:
          destination: logExchange
          content-type: application/json
          binder: defaultRabbit
          producer:
            exchangeType: direct
            acknowledge-mode: auto123
  rabbitmq:
    addresses: 149.28.142.66

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8600/eureka/
