server:
  port: 8605
spring:
  application:
    name: stream-producer
  cloud:
    stream:
      binders:
        defaultRabbit: # 表示定义的名称，用于于binding整合
          type: rabbit # 消息组件类型
      default-binder: defaultRabbit

      bindings: # 服务的整合处理
#        output: # 这个名字是一个接收通道的名称
#          destination: logExchange # 表示要使用的Exchange名称定义
#          content-type: application/json # 设置消息类型，本次为对象json，如果是文本则设置“text/plain”
#          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
        logOutput:
          destination: testExchange
          content-type: application/json
#          binder: defaultRabbit
#      rabbit:
#        bindings:
#          logOutput:
#            producer:
#              routing-key: test-key
#              acknowledge-mode: auto
  rabbitmq:
    addresses: 149.28.142.66

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8600/eureka/
