server:
  port: 8104

spring:
  application:
    name: oc-stream-log
  cloud:
    stream:
      binders:
        defaultRabbit: # 表示定义的名称，用于于binding整合
          type: rabbit # 消息组件类型
      default-binder: defaultRabbit
#          environment: # 设置rabbitmq的相关的环境配置
#            spring:
#              rabbitmq:
#                addresses: 149.28.142.66
#                username: guest
#                password: guest
#                virtual-host: /
      bindings: # 服务的整合处理
#        input: # 这个名字是一个接收通道的名称
#          destination: logExchange # 表示要使用的Exchange名称定义
#          content-type: application/json # 设置消息类型，本次为对象json，如果是文本则设置“text/plain”
#          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
        logInput: # 这个名字是一个接收通道的名称
          destination: testExchange # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为对象json，如果是文本则设置“text/plain”
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
          group: test-group
          consumer:
            max-attempts: 1
      rabbit:
        bindings:
          logInput:
            consumer: # 进行消费端配置
              requeue-rejected: true #当把这个设置为true的时候需要把max-attempts: 设置为1，要不如果没有完全消费信息时依然会把信息从队列里移除，为true后相当于错误时候无限轮询
#              acknowledge-mode: manual
#              bindingRoutingKey: study-key # 设置一个RoutingKey信息
  rabbitmq:
    host: 149.28.142.66


eureka:
  client:
    service-url:
      defaultZone: http://149.28.142.66:8080/cloud_server/eureka