eureka:
  client:
    service-url:
      defaultZone: http://localhost:8600/eureka/



spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          #          uri: https://github.com/lsjkobe/SpringCloud_ConfigService_Config.git
          uri: D:\leo.li\local_git\springcloud_config
#          username: leoli
#          password: li936339745


  rabbitmq:
    host: 149.28.142.66

management:
  endpoints:
    web:
      exposure:
        include: "health, info, bus-refresh"
