eureka:
  client:
    service-url:
      defaultZone: http://localhost:8091/eureka/



spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          #          uri: https://github.com/lsjkobe/SpringCloud_ConfigService_Config.git
          uri: E:\local_git\springcloud_config
#          username: leoli
#          password: li936339745

