server:
  port: 8602

eureka:
  client:
    service-url:
      defaultZone: http://149.28.142.66:8080/cloud_server/eureka

spring:
  application:
    name: feign-service

  servlet:
    multipart:
      max-file-size: 100MB



feign:
  hystrix:
    enabled: true

#  修改feign的超时时间
  client:
    config:
      default:           #服务名，填写default为所有服务
        connectTimeout: 1000
        readTimeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

# To set thread isolation to SEMAPHORE
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE